name: Jekyll Themes
url: http://bellsky.github.io/webdev2022
baseurl: webdev2022
description: Insert tagline here

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
